---
editor_options: 
  chunk_output_type: console
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r collect_nacre_data}
chem_dt_long <- valve_dt %>%
  group_by(id, transect) %>%
  mutate(
    dt = purrr::map2(distance, chemistry, 
                     ~ left_join(.x, .y, by = "obs") %>% 
                       select(-idref_method, -idt, -obs, -best_method) %>%
                       tidyr::gather(key = "element", value = "value", 
                                     -distance, -layer, -annuli)
                     ),
    drawer = purrr::map_dbl(measures, ~ .x$drawer[1])
      
  ) %>%
  select(drawer, id, transect, dt) %>%
  tidyr::unnest()


nacre_data <- chem_dt_long %>%  
  group_by(drawer, id, transect, element) %>%
  # Filter to transects that have at least one nacreous layer observation
  # Keep both nacreous and epoxy values
  filter((sum(layer == "ncr", na.rm = TRUE) > 1), layer %in% c("ncr", "ipx")) %>%
  mutate(
    idt              = paste(id, transect, sep = "_"),
    use_AB_analysis  = idt %in% has_AB_ids
  )  %>%
  inner_join(outcomes, by = "id") %>%
  mutate(idt = paste(id, transect)) %>%
  group_by(element) %>%
  tidyr::nest()
```

```{r}
annotate_nacre <- function(.p, .data, .value_var){
  # Annotation settings
  nacre_anno <- expression(Nacre*symbol("\256"))
  epoxy_anno <- expression(symbol("\254")*Epoxy)
  yanno      <- diff(range(.data[[.value_var]]))*.025

  .p + 
  annotate(geom = "text", x = 0, y = -yanno, label = as.character(epoxy_anno),
           hjust = 1, size = 3, color = "grey50", parse = TRUE) +
  annotate(geom = "text", x = 0, y = -yanno, label = as.character(nacre_anno),
            hjust = 0, size = 3, color = "grey50", parse = TRUE)
}

plot_nacre <- function(.data, .title, .include_title = FALSE, 
                       .ylabel, .xlabel = expression(mu*m),
                       .value_var = "value", 
                       .distance_var, .distance_filter = NULL,
                       .facet_formula = ~ species,
                       .scales  = "fixed",
                       .add_anno = TRUE){
  if(!is.null(.distance_filter)){
    .data <- filter(.data, 
                    !! rlang::sym(.distance_var)  > .distance_filter[1], 
                    !! rlang::sym(.distance_var)  < .distance_filter[2] )
  }
  


  # organize plot
  ggplot(
    .data,
     aes(x = !! rlang::sym(.distance_var), y = !! rlang::sym(.value_var), 
         group = idt, color = annuli)) + 
    geom_hline(yintercept = 0, color = "grey90") + 
    geom_vline(xintercept = 0, color = "grey90") + 
    geom_line(alpha = .5, size = .5) +
    scale_color_discrete(guide = FALSE) + 
    scale_y_continuous(
      name = .ylabel
    ) + 
    scale_x_continuous(
      name = .xlabel
    ) + 
    facet_grid(.facet_formula, scales = .scales) + 
    theme_classic() +
    theme(
      axis.line.x = element_blank(),
      axis.line.y = element_line(color = "grey90"),
      axis.ticks  = element_line(color = "grey90"),
      axis.text   = element_text(color = "grey75"),
      strip.background = element_blank()
    ) -> p
  
  if(.include_title){
     p <- p + ggtitle(.title) 
  }
  
  if(.add_anno){
    p <- annotate_nacre(p, .data, .value_var)
  }
  
  p
}
```


```{r}
show_plots <- function(.prelabel){
  plots <- paste0(list.files("img", full.names = TRUE))
  plots <- plots[grepl(.prelabel, plots)]
  
  replacements <- c("", "")
  names(replacements) <- c("\\.png", sprintf("img/%s_", .prelabel)) 
  names(plots) <- str_replace_all(plots, replacements)
  
  bsselect(plots, type = "img", selected = "As_ppm_m75", 
           frame_height = "200",
           live_search = TRUE, show_tick = TRUE)
}
```


```{r, eval = FALSE}
plot_nacre(
      nacre_data$data[[1]], 
     .ylabel = nacre_data$element[[1]], 
     .title = "Elemental conc anchoring at Epoxy/Nacre edge",
     .distance_var = "distance", 
     .distance_filter = c(-100, 200)) 
```

## All available valve-transects: epoxy/nacre edge

Displaying the first 100$\mu$m of epoxy and 200$\mu$m of nacre for all valve-transects with some observations within the nacre. Each line = one valve-transect.



```{r, echo = FALSE}
invisible(purrr::map2(nacre_data$data, nacre_data$element, function(x, y){
    p <- plot_nacre(
      x, 
     .ylabel = y, 
     .title = "Elemental conc anchoring at Epoxy/Nacre edge",
     .distance_var = "distance", 
     .distance_filter = c(-100, 200),
     .facet_formula = species ~ .,
     .scales = "free_y",
     .add_anno = FALSE) 
    ggsave(file = sprintf("img/epoxy_nacre_free_scale_%s.png", y), width = 7, height = 5, dpi = 300)
}))
```

```{r}
show_plots("epoxy_nacre_free_scale")
```

Showing the same data but faceting by drawer rather than species:

```{r, echo = FALSE}
invisible(purrr::map2(nacre_data$data, nacre_data$element, function(x, y){
    p <- plot_nacre(
      x, 
     .ylabel = y, 
     .title = "Elemental conc anchoring at Epoxy/Nacre edge",
     .distance_var = "distance", 
     .distance_filter = c(-100, 200),
     .facet_formula =  drawer ~ .,
     .add_anno = FALSE) 
    ggsave(file = sprintf("img/epoxy_nacre_drawer_%s.png", y), width = 7, height = 5, dpi = 300)
}))
```

```{r}
show_plots("epoxy_nacre_drawer")
```

After applying hampel filter to data by drawer:


```{r, clean_drawer5}
nacre_data2 <- nacre_data %>%
  mutate(
    data = purrr::map(data, ~ .x %>% group_by(drawer, id, transect) %>%
                        mutate(value = pracma::hampel(x = value, k = 8)$y))
  )
```

```{r, echo = FALSE}
invisible(purrr::map2(nacre_data2$data, nacre_data2$element, function(x, y){
    p <- plot_nacre(
      x, 
     .ylabel = y, 
     .title = "Elemental conc anchoring at Epoxy/Nacre edge",
     .distance_var = "distance", 
     .distance_filter = c(-100, 200),
     .facet_formula =  drawer ~ .,
     .add_anno = FALSE) 
    ggsave(file = sprintf("img/epoxy_nacre2_drawer_%s.png", y), width = 7, height = 5, dpi = 300)
}))
```

```{r}
show_plots("epoxy_nacre2_drawer")
```

