---
title: "LOG"
output: pdf_document
---

## 20160529 

* Reviewing existing plot fors As, Ba, and Cd.
  * As:
    * some of the median values in `As_ppm_m75_median_alltransect` are < 0. I'm not sure I understand why values would be < 0. TODO: Ask Nathan about this.
    * scale on mean and sd plots too wide to distinguish anything due to outlier in A. rav at baseline, transect 1.
    * pattern in existing plots that of possible note: median value tended not change from transect 2 to 1 (older to newer) for the most part, but in a few sites most of the individuals did change (see `As_ppm_m75_median_alltransect`). See note above about median values < 0, so I don't think this means much. 
  * Ba:
    * review further: in A. rav in transect 1 Ba levels are consistent across the transect. In L. fas, however, Ba levels decrease moving from inner to outer. Also, LiTN appears to have lower concentrations than the Tuck (also compare to baseline). See `Ba_ppm_m138_log1p_transect1` and `Ba_ppm_m138_identity_transect1`. The same patterns of lower levels in the baseline L. fas can also be seen in `Ba_ppm_m138_mean1p_alltransect` and `Ba_ppm_m138_mean_alltransect`. However, transect 2 in the experimental L. fas is higher than the baseline animals. The A. rav don't appear much different across rivers, baseline or transects.
  * Cd:
    * In terms of median values, animals were had similar values across transects (see `Cd_ppm_m11_median_alltransect`).
    * maybe: variability increases in moving from transect 2 to 1
  * Co:
    * similar to Cd. nothing obvious. In `Co_ppm_m59_median_alltransect`, it looks like there are two groupings to the values: ~0.15 and ~ -0.05.

## 20160601

* created drafts of `VAR_cumsum_transect1.pdf`. I think some variation on these may prove useful.

## 20160608

* Cr:
    * values for transect 1 in L. fas appear more variable across the transect than in either river in `Cr_ppm_m53_identity_transect1` (and `log1p`), but on average values seem similar as seen in other plots
* Cu_m63:
    * baseline values in L. Fas appear lower than either river in `...cumsum...`
    * Cu increases toward Periostracum
    * L. fas generally did not change much across transects. A few A. rav did change both in terms of mean and median as seen in `Cu_ppm_m63_median_alltransect`
    * this might be looking at further. See `Cu_ppm_m63_stdized` there are a few specimens that have more spikes and the spikes increase moving from transect 3 - 2 - 1. How does this vary across sites?
      * QUESTION: do the locations of the Cu deposits map across transects within a specimen
* Cu_m65:
   * not much different than Cu_m63
* Fe:
  * `Fe_ppm_m57_identity_transect1` shows higher Fe in transect 1 in baseline A. rav (on average). 
    * this can also be seen in `Fe_ppm_m57_mean_alltransect` (compare baseline transect 1 to others).
    * QUESTION: why do baseline A rav have generally higher Fe across all transects?
* Hg:
    * explore further: `cumsum` plots (in next iteration of plots)
    * nothing striking in current exploratory plots
* Kr83:
    * maybe? increasing variabliity in mean levels moving from transect 3-2-1 (see `Kr83_CPS_mean1p_alltransect` or similar)
    
## 20160612

* Mg_m24:
    * in transect 1, A.rav appear to have more Mg at the inner part of the shell; in L. fas, Mg, appears to accumulate towards periostracum. (`_log1p_transect1`)
    * maybe: more variability across transects in non-baseline specimens (`_mean1p_alltransect`).
    * it appears that only 1 or 2 specimens in the LiTN have a larger amount of Mg. The rest appear similar.
* Mg_m25:
    * not much different than Mg_m24
* Mn:
    * A. rav tends to accumulate more than L. fas
    * Interesting: L. fas at LiTN 1 all had greater mean Mn than other sites `_mean_alltransect`
    * greater variability in mean levels in transect 1 in A. rav river specimens compared to baseline specimens (`mean_alltransect` and similar).
* Mo:
    * no obvious patterns
* Ni:
    * maybe: more variability across transects in non-baseline specimens (`_mean1p_alltransect`).
* Pb:
    * maybe: more accumulated in LiTN specimens on average than Tuck in both A. rav and L. fas (`_cumsum_transect1` and `log1p_transect1`).
* Se:
    * no obvious patterns
* Sn: 
    * no obvious patterns
* Sr:
    * river L. fas specimens have greater levels in transect 1 compared to baseline transect 1 (`_identity_transect1` and `cumsum_transect1`). river A. rav specimens may have lower levels in transect 1 compared to baseline transect 1.
* U:
    * no obvious patterns
* Zn:
    * river A. rav specimens may accumulate Zn moving from transect 3 -> 2 -> 1 (`_mean_alltransect`)
    
* moving forward:
    * link concentration to outcomes (live/die)
    * would be helpful to have:
      * data from more transects
      * distance between transects: can I use the images in the scan maps file? are the image all the same scale?
    

## 20160713

* thinking about what information to get from scans
* From Nathan's notes:  
> In all cases the scans run from the inner shell to the outer shell/periostracum, and scans begin and end in the bounding epoxy.  For shells with multiple traverses, the traverses are numbered hinge-ward, for example (1) outer edge, (2) closer to hinge, (3) even closer to the hinge, etc.  By this approach, equivalent or increasingly older shell layers are encountered in hinge-ward traverses.  

* Gather information on each transect:
   * id 
   * transect
   * distance from outer edge to start of transect on periostracum
   * distance from outer edge to end of transect on inner shell
   * direction: along shell or perpendicular
   * count of 'rings' crossed
   * distance from start of transect to start of prismatic layer (this may be difficult to measure)
   * some indicator of whether the transect is comparable to other transects: a category of transects maybe? i.e. group transects into comparable classes. 

## 20160727

* went through shell scans and manually identified A. rav shells and transects that appear comparable. These are in `analysis_shells.csv`.
* created exploratory plots in `/V002` that look at the means of element values within the first 100 $\mu$m of the inner edge (which should be roughly the most recent growth)

## 20160820

* developed preliminary generalized additive models treating elements as outcomes. See `shells/elements/V001`.
* In looking at this output, I think I do need to figure out where the growth edges are for each shell. 
* There appears to be one shell at LiTN3 that has a big spike in a lot of elements about 400 micrometers from the inner edge. Why is that?
* In most shells, Pb is greater near the inner edge. Is this an artifact of how the inner edge was identified based on my assumptions?

## 20160821

* added mortality models to output

## 20160822

* note from Scott: Eighty-two A. raveneliana were obtained from the Tuckasegee river near Barkers Creek (35.381479, -83.288928) -- near site 2

## 20160824

* a note from Scott:

> I did not prep the shells (clean, etc.) prior to cutting. Everything on the outside would have come along with the shells. As for the dead ones, most of them we pulled them out of the cages in August 2013. They died sometime between July and August of that year. I'll have to go back through the records to check exact dates. All shells, at least in the processing for this part of the project, were treated the same. The mussels sampled in September/October 2013 and May 2014 were sampled the same way. We first took pictures of all the animals outside of the shells, opened them, then took a picture inside of the bodies. We then removed the bodies and placed the empty shells in a whirl-pak. These were placed on ice in a cooler until we got back to the lab and placed them into the 4C refrigerator. They remained in there until processing in the histology lab at the vet school. As for the dead ones, some were empty shells when we found them, others still had tissues inside. If they had tissues, we removed the tissues and placed them into 70% EtOH. The shells, both with and without tissues, were placed in a whirl-pak on ice until we got back to the lab and stored them at 4C. All shells were in the water prior to placing them in whirl-paks so none were allowed to dry before placing them in there. That is not to say that some did dry in the refrigerator prior to cutting the shells. Again, every shell was treated the same way. 

> As for the dead ones being more porous, does Nathan have images of all the shell sections? If so, you may be able to go back and see if there were more pores in the dead vs. living animal's shells. I don't know of that happening as the shells are not living tissue and unless there was enough water flow to erode the shells in that short of time I would doubt that there would be issues with that. If there is, that may be something to look at more as it may be an indicator of unhealthy animals which could be really interesting.


## 20160828

* further refinements to summary pdfs by element `V004`

## 20161017

* found mistake in selecting transects: some transects had been selected twice and thus repeated in the dataset.
* trying out computing element/CA ratios to see if normalizing to CA content makes a difference. Just looking at this graphically for now.
* incorporated this changes in `V005`.

## 20161105

* added L. fasciola to summary pdfs. Added to `V006`.

## 20161216

* working on reading measurements from shell scans. The original scan was one large .ai. separating this into separate files for each shell.

## 20170103

* spent an hour or so looking more closely at mapping between laser measurements and shell scans. My hope was that I could measure transects in the shell scans and link that fairly closely to the laser measurements. To be successful, though, I would need measurements to line up with 5-10 $\mu$m of accuracy. This would be difficult. Even just comparing length of entire transect measurement, the two ways of measuring distance (laser distance and measuring the shell in the .ai file) yield differences of up to 50 $\mu$m. Part of this is due to the challenge of identifying where the shell begin and epoxy ends. In the laser measurement, these bleed into one another. In the scans, epoxy is not visible. Another challenge is that the region of most recent growth is generally right in this boundary region.

## 20170104

* found error in `V006`: had failed to subset to *A. rav* in all mortality models. fixed in `V007`.

## 20170405

* See `transect_alignment_study` folder for current direction of research.
* Selected valves for this study and moved images to respective directories.
