---
title: Trace elements accrued in endangered freshwater bivalves in two North Carolina streams
author:
- Bradley C. Saul
- Nathan R. Miller
- Heather Gunn
- Michael Walter
- Scott Salger
- Mike Gangloff
- Jay F. Levine
bibliography: elktoe.bib
output: 
  pdf_document:
    number_sections: true
header-includes:   
- \usepackage{amsmath, setspace}
- \usepackage{multirow}
- \graphicspath{ {figures/} } 
abstract: TBD
keywords: LA-ICP-MS, Alasmidonta, add more
---

\doublespacing

# Introduction 

After major hurricane-related flooding in 2004, the population of Federally endangered Appalachian Elktoe (*Alasmidonta raveneliana*) in North Carolina's Little Tennessee River declined precipitously, but within the same watershed's Tuckasegee River populations appear stable. Reasons for the decline are unclear [@jarvis2011water; @miller2013concentrations; @pandolfi2016effects]. To determine how river-specific factors may be associated with health and physiological outcomes, we conducted a completely randomized experiment by assigning eighty-two *A. raveneliana* along with an equal number of hatchery-raised Wavy-Rayed Lampmussel (*Lampsilis fasciola*) to sites within each river.

Similar to tree rings, bivalve shells archive some aspects of their environmental history and have been used as bioindicators of pollution [@markich2002freshwater; @brown2005freshwater; @shoults2014resolution]. Exposure to certain heavy metals have been shown to increase morbidity and mortality in freshwater bivalves [@naimo1995a-review]. @miller2013concentrations evaluated sediment concentrations of Cu, Cr, Ni, and Zn in the Little Tennessee and Tuckasegee. When considered with the chemical concentrations of *A. raveneliana* shells measured by @jarvis2011water, they found these elements (Cu in particular) unlikely to be the primary culprit in the *A. raveneliana* decline.

In this paper, we ask whether and to what degree the exposure to the experimental sites modified the accretion of twenty trace elements in specimens’ valves. We demonstrate how chemical profiles obtained by laser ablation inductively coupled plasma mass spectrometry (LA-ICP-MS) [@pozebon2014review] can be aligned with anatomical features of the valves, thus making comparisons of concentrations from specific valve layers possible. Since the assignment to sites was completely randomized, we use the randomization distribution to draw inference. While this method of statistical inference dates back to Fisher [CITE], it is less common to use this approach with multivariate data. 

...TODO...
* Our answers represent important contributions to scientific understanding of unionid physiology, ecological experiments, and … . 
* They also lead us to propose hypotheses as to the decline of *A. raveneliana*.

The paper is organized as follows. Section \ref{materials-and-methods} outlines the experimental design, data collection, anatomy/chemical alignment procedurew, and the statistical methods. Section \ref{results} provides results. In Section \ref{discussion}, we discuss the implications of our results, hypothesize on causes of the *A. raveneliana*, and suggest future research. Data and code are available at the study website (ADD LINK) 

# Materials and methods

## Study Specimens

Eighty-two *A. raveneliana* specimens were drawn from the Tuckasegee river. Ten were killed for baseline comparisons, and the remaining 72 were randomly assigned to 6 experimental sites (3 on each river) [INSERT FIGURE OF SITES]. The same number of *L. faciola* specimens were taken from the NC Wildlife Resources' Marian hatchery and were placed in a separate cage alongside the *A. raveneliana* as control specimens. The specimens were deposited at each site in April 2013. Due to high mortality at some sites, the *A. raveneliana* were pulled six months later. Some of the *L. faciola* were pulled at the same time, while the remaining were extracted the following Spring. 

The mussels were held in plastic mesh cages anchored in the bottom substrate. All animals were individually identified with randomly selected numeric identification tags glued to the shells. Shell metrics and weight were obtained before and after deployment in the cages. After the experiment, a small (approximately 0.5 inch) section of the right valve from each animal was removed and embedded in plastic for laser ablation analyses.

## LA-ICP-MS

As youngest growth was of principal interest, we targeted growth parallel transects from the outer margins of valves, away from the umbo. For thicker valves we also analyzed additional offset scans to evaluate reproducibility and include older growth. In most cases, the entire preserved growth history was recorded by making multiple offset traverses (Figure \ref{}). Along each transect, readings were taken every 2.88$\mu$m. All transects moved from the inner to the outer shell, parallel to the growth direction, beginning and ending in epoxy. The scans varied in terms of residing solely with the outer prismatic layer and periostracum, or being compound scans initiating in the nacreous layer. 

Each transect resulted in a chemical time-series for each analyte (concentration vs. distance; a matrix of ~7000 concentration measurements per mm). For data reduction (?) we assumed a stoichiometric CaCO3 composition (40.0432 wt% Ca) and did not adjust for mineralogy (aragonite vs. calcite). We used USGS MACS-3 (synthetic aragonite) as the primary calibration standard, and analyzed NIST 614 (trace elements at ~1 ppm) and NIST 612 (trace elements at ~35 ppm). For drift compensation, each hour of data collection on unknowns was bracketed by analyses of each standard (in duplicate). We surveyed twenty industrial metals and bio-metals: Mg, Ca, Cr, Mn, Fe, Co, Ni, Cu, Zn, As, Se, Kr (for Se interference correction if detected), Sr, Mo, Cd, Sn, Ba, Hg, Pb and U. 
Analyses were conducted at the University of Texas at Austin using an ESI New Wave Research NWR193 excimer laser coupled to an Agilent 7500ce ICP-MS. 

## Chemical/Anatomical Alignment

[ADD DESCRIPTION OF MEASURING ANATOMY]

To align anatomical features with chemistry data, several methods were used to identify valve edges within the chemistry data based on algorithmic detection in mean and variance [@killick2014changepoint; @killick2016changepoint] or the minimum (or maximum) [@borchers2018pracma] of Ca43_CPS, Pb208_CPS, or the ratio of the two. The difference of the distance between these detected edges and the distance between the valves edges measured from high resolution scans was then computed. For each valve, the method that minimized this distance was then used to register the anatomy in the chemical data.

* applied lower limit of detection by taking the mean lower limit of detection with each of the seven batches of the LA-ICP-MS

## Statistical Analyses

For each element, we tested the hypothesis that $\text{log}(\text{mol/Ca mmol})$ trajectories within the nacre did not differ between any of the sites. Inference was drawn using the randomization distribution and a test statistic of the deviance between two nested Generalized Additive Mixed Models (GAMM): one including terms for experimental sites and one without.

# Results

## Description of survival

## Chemicals 

Preliminary results revealed differences in nacre elemental trajectories of the experimental sites. In A. raveneliana, for example, trajectories of Mn differ in at least one experimental site (p-value = 0.002). Visual examination of the predicted values from a GAMM model show systematically higher levels in the region of most recent growth in Little Tennessee specimens. Results for the comparatively younger L. fasciola specimens show a similar though not as obvious pattern (p-value = 0.054). 

## Elements associated with rivers and sites

Figure XX shows effect estimates and 9X% confidence intervals of the contrast of baseline to Tuck, baseline to LiTN, and Tuck to LiTN. 

## Elements associated with morbidity/mortality

Figure XX shows effect estimates from logistic regressions. Only elements with a statistically significant effect (or p < 0.1?) are shown; remaining are in Supplementary Materials.

# Discussion

Our analysis showed differences between the experimental sites in Mn concentrations accumulated during the study period. Manganese is an essential trace element with important roles in numerous enzymatic pathways that could have harmful effects on freshwater bivalves. The completely randomized design allows for robust, internally valid inference; however, further analyses with these data are needed to: 1) Examine other observed differences in elemental concentrations; 2) Rule out possible confounding such as seasonal and batch effects; and 3) Explore sources of these elements within the watersheds.

* Based on how valves grow [@checa2000a-new-model], we should have captured the most recent growth

We have shown that …

* XXX, YYY, and ZZZ appeared in greater concentration in LiTN valves. Notably, XXX has been shown to have physiological effect AAA, and so on for YYY and ZZZ.
*

* associations with morbidity/mortality are not causal effects. would be causal if...
* associations of elements and river/site do have causal interpretation under following assumptions <-- worth mentioning?


## Limitations

* discussion of cage effect

## ETC

* @jackson2003laser experimentally fed contaminated fish to banded water snakes and showed LA-ICP-MS on tail tissue and showed LA-ICP-MS was able to differentiate between treatments.


# References