---
editor_options: 
  chunk_output_type: console
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
library(shiny)
library(stringr)
library(bsselectR)
```

```{r load_data}
chem_dt      <- readRDS("../data/valve_analysis.rds")
chem_dt_long <- readRDS("../data/valve_analysis_long.rds")
annuli_avail <- readRDS("../data/valve_annual_layer_availability.rds")
outcomes     <- readRDS("../data/valve_mussel_info.rds")
```

# Introduction

There are `r nrow(outcomes)` individual mussels and `r nrow(annuli_avail)` transects available for analysis. The following table provides basic information about each valve.

```{r, results = "asis"}
outcomes %>%
  select(id, species, river, site_num, n_annuli) %>%
  DT::datatable()
```

Number of valves available per species per study site:

```{r, results = "asis"}
outcomes %>%
  group_by(species, site) %>%
  summarise(n = n()) %>%
  tidyr::spread(key = species, value = n) %>%
  knitr::kable()
```


