---
title: "Untitled"
author: "Bradley Saul"
date: "10/14/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(VGAM)
knitr::opts_chunk$set(echo = TRUE)
source("10a_analysis_functions.R")
```

```{r prepare_data}
dt <- filter_valves(.species = "A. raveneliana", .has_annuli = c("A"),
                    .river = c("Tuckasegee", "Little Tennessee")) %>%
  mutate(analysis_dt = purrr::map(valve_filterFUN, 
                                  ~ .x(.layer = "ncr",  .annuli = c("A"),
                                       .inner_buffer = 15, .outer_buffer = 10))) %>%
  select(id, transect, site, site_num, river, species, dead, final_status, n_annuli, analysis_dt) %>%
  mutate(analysis_dt = purrr::map(analysis_dt,  ~.x %>% convert_to_long())) %>%  
  tidyr::unnest() %>%
  filter(grepl("ppm", element)) %>%
  group_by(id, transect, site, site_num, river, species, dead, final_status, n_annuli, element) %>%
  summarise(value = max(value))
```

```{r, plotting_functions}
make_dotplot <- function(.data){
  ggplot(data = .data, 
         aes(x = site_num, y = value)) + 
    geom_point() + 
    facet_grid( ~ river)
}

```


```{r make_plots}
elements <- unique(dt$element)

for(i in seq_along(elements)){
  temp <- dt %>% filter(element == elements[i]) %>%
    group_by(id) %>%
    filter(value == min(value))
  p <- temp %>% make_dotplot() + ggtitle(elements[i]) 
  print(p)
}

```


```{r}
temp <- dt %>% filter(element == elements[16]) %>%
  group_by(id) %>%
  filter(value == min(value))
fit1 <- vglm(value ~ site, gev(zero = 3),
    data = temp, trace = TRUE, maxit = 10000, imethod = 2)


coef(fit1, matrix = TRUE)
coef(fit1)/sqrt(diag(vcov(fit1)))
head(fitted(fit1))
y <- predictvglm(fit1, newdata = temp, type = "response")

qqplot(temp$value, y[ , 2])

```
