---
title: "Untitled"
author: "Bradley Saul"
date: "1/3/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(grid)
library(gridExtra)
library(ggbeeswarm)
knitr::opts_chunk$set(echo = TRUE)
source("10a_analysis_functions.R")
```

# Nacre

```{r}
ncr_a <- elktoe_ncr(
  .a      =  c("A"),
  .f      = quos(n() > 10),
  .dtrans = function(x) {max(x) - x},
  .vtrans = function(x) {log10(pmax(0, x) + 1)}
) %>%
  mutate(plot = "ncrA")

ncr <- elktoe_ncr(
  .f      = quos(n() > 10),
  .dtrans = function(x) {max(x) - x},
  .vtrans = function(x) {log10(pmax(0, x) + 1)}
) %>%
  mutate(plot = "ncrall")

psm <- elktoe_psm(
  .f      = quos(n() > 10),
  .dtrans = function(x) {max(x) - x},
  .vtrans = function(x) {log10(pmax(0, x) + 1)}
) %>%
  mutate(plot = "psm")

pio <- elktoe_pio(
  .f      = quos(n() > 10),
  .dtrans = function(x) {max(x) - x},
  .vtrans = function(x) {log10(pmax(0, x) + 1)}
) %>%
  mutate(plot = "pio")

dt <- bind_rows(ncr_a, ncr, psm, pio) 

dt_summary <- dt %>%
  group_by(plot, site, river, site_num, dead, id, element) %>%
  summarise(
    mean   = mean(value),
    median = median(value),
    sd     = sd(value)
  )  %>% 
  group_by(plot, element, river, site_num) %>%
  mutate(
    plot_order = rank(mean),
    conf_lo    = mean - sd,
    conf_hi    = mean + sd
 ) 

```

```{r}
plot_oall <- function(data){
  ggplot(
    data = data,
    aes(x = site, y = mn)) + 
    geom_point() +
    geom_segment(aes(xend = site, y = lb, yend = ub)) +
    scale_y_continuous(
      "Mean of means +/- 1 SD(means)"
    ) + 
    theme_bw() + 
    theme(
      axis.title.x = element_blank()
    )
}


```

```{r}
plotting_layers <- dt_summary %>% 
  group_by(plot, element) %>%
  tidyr::nest() %>%
  mutate(
    p    = purrr::map2(data, plot, ~ plot_a(.x, .y, include_guide = FALSE)),
    oall = purrr::map(
      data,  ~ .x %>%
        group_by(river, site_num, site) %>%
        summarise(
        mn = mean(mean),
        sd = sd(mean),
        md = median(median),
        lb = mn - sd,
        ub = mn + sd)
      ),
    poall = purrr::map(oall, ~ plot_oall(.x))
  ) %>%
  group_by(element) %>%
  tidyr::nest()  %>%
  mutate(
    plot  = purrr::map2(
      data, element, function(x, y){
        ti <- textGrob(label = y)
        tr <- arrangeGrob(grobs = x$p, ncol = 4)
        br <- arrangeGrob(grobs = x$poall, ncol = 4)
        out <- arrangeGrob(ti, tr, br, nrow = 3, heights = c(.5, 5, 3))
      })
  )


lapply(seq_along(plotting_layers$element), function(i){
  ggsave(filename = sprintf('programs/tempPDF/%s.pdf' , plotting_layers$element[i]),
         plot = plotting_layers$plot[[i]],
         height = 8.5, width = 11, units = 'in')
})








```


```{r}
library(geepack)
library(lme4)

# z <- z %>% arrange(idt)
# test <- geeglm(value ~ site, data = z, id = idt, corstr = "ar1")

test <- lmer(value ~ site + (id|transect), data = z)
str(summary(test)$coefficients)

ggplot(data = y,
       aes(x = river, y = mn)) + 
         geom_point()
# plot_point_by_river_site(x)

```
