---
title: "Untitled"
author: "Bradley Saul"
date: "11/24/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(survival)
vd <- readRDS("data/valve_data.rds")
al <- readRDS("data/valve_annual_layer_availability.rds")
mi <- readRDS("data/valve_mussel_info.rds")
```


```{r}
annuli_distances <- vd %>%
  right_join(
    select(filter(al, A == TRUE), id, transect), by = c("id", "transect")
  ) %>%
  select(id, transect, distance) %>%
  tidyr::unnest() %>%
  filter(layer == "ncr") %>%
  group_by(id, transect, annuli) %>%
  summarise(
    d = max(distance)
  ) %>%
  mutate(
    d = d - lag(d, default = 0)
  )
```


```{r}
dt <- annuli_distances %>%
  filter(annuli == "A") %>%
  left_join(
    select(mi, id, site, river, species, dead, n_annuli),
    by = "id"
  ) %>%
  filter(species == "A. raveneliana", site != "Baseline") %>%
  left_join(
    annuli_distances %>% filter(annuli == "B") %>%
       select(id, transect, dB = d),
    by = c("id", "transect")
  ) %>%
  group_by(id) %>%
  filter(transect == min(transect))

dt$SurvObj <- with(dt, Surv(d, dead))

x <- survfit(SurvObj ~ river, data = dt)
plot(x)


m <- coxph(SurvObj ~ river + n_annuli, data = dt)
summary(m)
```


```{r}
longdt <- vd %>%
  select(id, transect, distance, chemistry) %>%
  tidyr::unnest() %>%
  select(id, transect, distance, layer, annuli, contains("ppm")) %>%
  tidyr::gather(key = element, value = value, -id, -transect, -distance, -layer, -annuli) %>%
  filter(layer == "ncr", annuli == "A") %>%
  mutate(idt = paste0(id, transect)) %>%
  left_join(mi, by = c("id")) %>%
  group_by(id, transect) %>%
  filter(max(distance) > 40)

ids <- unique(longdt$idt)

mad_longdt <- longdt %>%
  group_by(id, transect, element) %>%
  filter(idt %in% ids, annuli == "A") %>%
  mutate(
    value = pracma::hampel(value, k = 4, t0 = 3)$y
  )

z <- mad_longdt %>%
  filter(distance > 35, distance < 100) %>%
  group_by(species, river, site, site_num, dead, id, transect, element) %>%
  summarise(m = quantile(value, .95))

unique(longdt$element)

ggplot(
  filter(z, species == "A. raveneliana"),
  aes(x = river, y = m, color = factor(dead))
) + geom_point(alpha = .5) + 
  facet_grid(element ~ ., scales = "free_y") + 
  theme(
    strip.text.y = element_text(angle = 0)
  )

```