---
title: "Untitled"
author: "Bradley Saul"
date: "10/14/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(elktoe)
library(ggplot2)
valve_analysis <- readRDS("data/valve_analysis.rds")
valve_analysis_long <- readRDS("data/valve_analysis_long.rds")
outcomes <- readRDS("data/valve_mussel_info.rds")
```

```{r}
valve_annual_layer_availability <- valve_analysis %>%
  group_by(id, transect) %>%
  filter(layer == "nacreous") %>%
  group_by(annuli, add = TRUE) %>%
  summarise(n = n() > 1) %>%
  tidyr::spread(
    key = annuli, value = n, fill = FALSE
  ) %>%
  mutate(
    has_A_and_B = A & B
  )

has_AB <- valve_annual_layer_availability %>%
  group_by(id) %>%
  mutate(transect = as.integer(transect)) %>%
  filter(has_A_and_B) %>%
  summarise(
    transect = as.character(min(transect))
  )

```

```{r}
nacre_data <- valve_analysis_long %>%  
  group_by(id, transect, element) %>%
  filter((sum(layer == "nacreous", na.rm = TRUE) > 1), transect == 1,
         (layer  == "nacreous" & !is.na(annuli)) | (layer == "epoxy" & distance < 150)) %>%
  mutate(
    dist_from_iedge = distance - min(distance[layer == "nacreous"])
  )  %>%
  inner_join(outcomes, by = "id") %>%
  mutate(
    site_num = if_else(site == "Baseline", 1L, as.integer(substr(site, 6, 6))),
    idt      = paste(id, transect)
  ) 

nacre_data %>%
  filter(is.na(annuli), dist_from_iedge > 0)

nest_nacre <- nacre_data %>%
  group_by(element) %>%
  tidyr::nest()

ggplot(
  nest_nacre$data[[1]],
  aes(x = dist_from_iedge, y = value, group = idt, color = annuli)
) + 
  geom_hline(yintercept = 0, color = "grey90") + 
  geom_vline(xintercept = 0, color = "grey90") + 
  geom_line(alpha = .5) +

  scale_x_continuous(
    limits = c(-100, 200)
  ) + 
  facet_grid( ~ species) + 
  theme_classic() +
  theme(
    axis.line.x = element_blank(),
    axis.line.y = element_line(color = "grey90"),
    strip.background = element_blank()
  )
  
  
```

```{r find_max_values}
## Compute the max value for transect 1 in the nacreous layer
max_values_long <- valve_analysis_long %>%
  right_join(has_AB, by = c("id", "transect")) %>%
  filter(!is.na(annuli) & layer == "nacreous") %>%
  group_by(element, id, transect, annuli) %>%
  summarise(max_value = max(value)) %>%
  rowwise() %>%
  mutate(annuli_order = which(annuli == LETTERS)) %>% ungroup %>%
  group_by(element, id, transect, annuli) %>%
  inner_join(outcomes, by = "id") %>%
  mutate(
    site_num = case_when(
      site == "Baseline" ~ 1L,
      TRUE ~ as.integer(substr(site, 6, 6)))
  ) %>%
  filter(
    species == "A. raveneliana"
  )

max_values_wide <- max_values_long%>%
  tidyr::spread(
    key = element, value = max_value
  )
```

```{r}
AB <- max_values_long %>%
  group_by(id, transect) %>%
  filter(annuli %in% c("A", "B"), transect == "1", species == "A. raveneliana") 

ids <- AB %>%
  summarise(
    has_A = any(annuli == "A"),
    has_B = any(annuli == "B")
  ) %>%
  filter(has_A, has_B) %>%
  dplyr::select(id, transect) %>%pull(id)
```

```{r}
make_max_plot <- function(.data){
  ggplot(
    data = .data, aes(x = -annuli_order, y = max_value, group = id)
  ) + 
    geom_line() +
   facet_grid(
    site_num ~  species + river
  )
}

make_max_cdf_plot <- function(.data){
  Fx <- ecdf(.data$max_value)
  plot(Fx)
}

make_max_plot(filter(max_values_long, element == "Pb208_CPS"))
filter(max_values_long, element == "Hg_ppm_m202") %>% 
  filter(annuli == "A") %>% make_max_cdf_plot()

```


```{r}
library(VGAM)
xx <- max_values_wide %>%
  filter(annuli %in% c("A", "B"), species == "A. raveneliana") %>%
  dplyr::select(id, annuli, river, site, site_num, Fe_ppm_m57) %>%
  tidyr::spread(key = annuli, value = Fe_ppm_m57)

# xx <- filter(max_values_wide, site != "Baseline", annuli == "A")

fit1 <- vglm(A ~ site + s(B, df = 4), gevff(zero = 2:3),
             data = xx, trace = TRUE, maxit = 10000, imethod = 2)
coef(fit1, matrix = TRUE)
coef(fit1)/sqrt(diag(vcov(fit1)))
head(fitted(fit1))
y <- predictvglm(fit1, newdata = xx, type = "response")

qqplot(xx$A, y[ ,1])

```
