---
title: "Nacre Displays"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

```{r load_data}
chem_dt      <- readRDS("data/valve_analysis.rds")
chem_dt_long <- readRDS("data/valve_analysis_long.rds")
annuli_avail <- readRDS("data/valve_annual_layer_availability.rds")
outcomes     <- readRDS("data/valve_mussel_info.rds")
```

```{r identify_valves_with_AB}
has_AB_ids <- annuli_avail %>%
  mutate(has_A_and_B = A & B) %>%
  group_by(id) %>%
  mutate(transect = as.integer(transect)) %>%
  filter(has_A_and_B) %>%
  summarise(transect = as.character(min(transect))) %>%
  tidyr::unite("idt", c("id", "transect")) %>% pull(idt)
```

```{r collect_nacre_data}
nacre_data <- chem_dt_long %>%  
  group_by(id, transect, element) %>%
  # Filter to transects that have at least one nacreous layer observation
  # Keep both nacreous and epoxy values
  filter((sum(layer == "nacreous", na.rm = TRUE) > 1), layer %in% c("nacreous", "inner_epoxy")) %>%
  mutate(
    dist_from_iedge  = distance - min(distance[layer == "nacreous"]),
    pdist_from_iedge = if_else(layer == "inner_epoxy", 
                               pdistance_layer - max(pdistance_layer[layer == "nacreous"]),
                               pdistance_layer),
    pdist_from_iedge = case_when(
      pdist_from_iedge == 0 & layer == "inner_epoxy" ~ pdist_from_iedge - 0.001,
      pdist_from_iedge == 0 & layer == "nacreous"    ~ pdist_from_iedge + 0.001,
      TRUE ~ pdist_from_iedge
    ),
    idt              = paste(id, transect, sep = "_"),
    use_AB_analysis  = idt %in% has_AB_ids
  )  %>%
  inner_join(outcomes, by = "id") %>%
  mutate(idt = paste(id, transect)) %>%
  group_by(element) %>%
  tidyr::nest()
```

```{r}

plot_nacre <- function(.data, .ylabel, .value_var = "value", .distance_var, .distance_filter = NULL){
  if(!is.null(.distance_filter)){
    .data <- filter(.data, !! rlang::sym(.distance_var)  > .distance_filter[1], !! rlang::sym(.distance_var)  < .distance_filter[2] )
  }
  
  # Annotation settings
  nacre_anno <- expression(Nacre*symbol("\256"))
  epoxy_anno <- expression(symbol("\254")*Epoxy)
  yanno      <- diff(range(.data[[.value_var]]))*.025

  # organize plot
  ggplot(
    .data,
     aes(x = !! rlang::sym(.distance_var), y = !! rlang::sym(.value_var), 
         group = idt, color = annuli)) + 
    geom_hline(yintercept = 0, color = "grey90") + 
    geom_vline(xintercept = 0, color = "grey90") + 

    annotate(geom = "text", x = 0, y = -yanno, label = as.character(epoxy_anno),
             hjust = 1, size = 3, color = "grey50", parse = TRUE) +
    annotate(geom = "text", x = 0, y = -yanno, label = as.character(nacre_anno),
             hjust = 0, size = 3, color = "grey50", parse = TRUE) + 
    
    geom_line(alpha = .5) +
    scale_color_discrete(guide = FALSE) + 
    scale_y_continuous(
      name = .ylabel
    ) + 
    scale_x_continuous(
      name = expression(mu*m)
    ) + 
    facet_grid( ~ species) + 
    theme_classic() +
    theme(
      axis.line.x = element_blank(),
      axis.line.y = element_line(color = "grey90"),
      axis.ticks  = element_line(color = "grey90"),
      axis.text   = element_text(color = "grey65"),
      strip.background = element_blank()
    )
  
}
```

```{r}

  
purrr::map2(nacre_data$data, nacre_data$element, function(x, y){
plot_nacre(x, .ylabel = y,
       .distance_var = "dist_from_iedge", 
       .distance_filter = c(-100, 200)) 
})

purrr::map2(nacre_data$data, nacre_data$element, function(x, y){
plot_nacre(x, .ylabel = y,
       .distance_var = "pdist_from_iedge", 
       .distance_filter = c(-1, 1)) 
})


  
  
```